### ISSUE TITLE
Incorrect TLS version part of the hash

### ISSUE THREAD

**Issue by mat1010** [O-X-L/haproxy-ja4-fingerprint#2]
The current way to compute the TLS version of the hash looks off to me.

The [documentation](https://github.com/FoxIO-LLC/ja4/blob/main/technical_details/JA4.md#tls-and-dtls-version) states

> The TLS version is shown in 3 different places. If extension 0x002b exists (supported_versions), then the version is the highest value in the extension. Remember to ignore GREASE values. If the extension doesn’t exist, then the TLS version is the value of the Protocol Version. Handshake version (located at the top of the packet) should be ignored.

This is also what happens here in the python example https://github.com/FoxIO-LLC/ja4/blob/main/python/ja4.py#L182 where the list of supported versions is gathered from the list in `handshake_extensions_supported_version`.

The current logic just takes the value from `ssl_fc_protocol_hello_id` straight away which, in my case, results in `12` while it should be `13`. I also did a tcpdump to verify it.

Unfortunately the `ssl_fc_extlist_bin` variable only holds the list of extensions, but not their values. Are you aware how to properly the the list?

**Comment by superstes** [comment]
Yeah - I did notice that too. That's why I added the variables to the debug section of the index.html

> Usage of [ssl_fc_protocol](https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#7.3.4-ssl_fc_protocol) or [ssl_fc_protocol_hello_id](https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#7.3.4-ssl_fc_protocol_hello_id) for part 2 of the fingerprint

An idea I had was to create a mapping table from `ssl_fc_protocol` (string - `TLSv1.3` for example) to the value we need.
But that too does not feel clean.

**Comment by mat1010** [comment]
Yes, you are right. Using [ssl_fc_protocol](https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#7.3.4-ssl_fc_protocol) would not be clean. It is explicitly mentioned in the documentation to "ignore" the value used for the initial handshake.

> Handshake version (located at the top of the packet) should be ignored.

Using [ssl_fc_protocol_hello_id](https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#7.3.4-ssl_fc_protocol_hello_id) as fallback, if the extension is not listed, would be fine from what I understand. I will also see if I can find a suitable approach.

**Comment by superstes** [comment]
I'm not into C but as reference - the source code:

* [ssl_fc_protocol](https://github.com/haproxy/haproxy/blob/v3.0.0/src/ssl_sample.c#L1604)
* [ssl_fc_protocol_hello_id](https://github.com/haproxy/haproxy/blob/v3.0.0/src/ssl_sample.c#L1890)
* [ssl_fc_ext_bin](https://github.com/haproxy/haproxy/blob/v3.0.0/src/ssl_sample.c#L1950)

**Comment by mat1010** [comment]
It seems that the tls extensions are not available through some kind of variable. I also asked on the [haproxy community slack](https://haproxy.slack.com/archives/C8EKNPFFH/p1724265582166009?thread_ts=1724265582.166009&cid=C8EKNPFFH) without  a positive outcome. I think we are having a similar issue in #4 since the `signature_algorithms` are also part of the [tls extensions](http://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml)

**Comment by superstes** [comment]
Yeah.. 😕

Have seen a `SSL_get_ex_data` in the source - that, to my understanding, fetches the value of a single extension.
But I've not seen any related function that would fetch all and make them available to us

**Comment by mat1010** [comment]
`ssl_fc_supported_versions_bin` is available in the [dev branch](https://github.com/haproxy/haproxy/tree/20240823-fc_supported_versions) right now the GREASE values are still part of the results but should be also removable by next week.
