### ISSUE TITLE
Missing check for signature algorithms

### ISSUE THREAD

**Issue by superstes** [O-X-L/haproxy-ja4-fingerprint#4]
Have not yet been able to implement the signature algorithm fetching method ([src1](https://github.com/FoxIO-LLC/ja4/blob/main/python/common.py#L147), [src2](https://github.com/FoxIO-LLC/ja4/blob/main/python/ja4.py#L215))

See: https://github.com/O-X-L/haproxy-ja4/blob/latest/ja4.lua#L163

Not sure if this is currently possible. See: [source code](https://github.com/haproxy/haproxy/blob/v3.0.0/src/ssl_sample.c)

**Comment by mat1010** [comment]
There's a[ dev branch](https://github.com/haproxy/haproxy/tree/20240823-fc_supported_versions) where `ssl_fc_sigalgs_bin` has been made available. I tested it already and the result looks good

```
local function signature_algorithms(txn)
    local algos = txn.c:be2hex(txn.f:ssl_fc_sigalgs_bin(), '-', 2)
    return algos
end
```
results in  `0403-0804-0401-0503`. Those values match the ones from [RFC8446](https://www.ietf.org/archive/id/draft-ietf-tls-rfc8446bis-03.html#section-4.2.3-3).

**Comment by superstes** [comment]
Nice :D
